apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: invoicing-api
  namespace: invoicing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: invoicing-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
