apiVersion: v1
kind: Service
metadata:
  name: invoicing-api
  labels:
    app.kubernetes.io/name: invoicing-api
    app.kubernetes.io/part-of: invoicing
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: invoicing-api
  ports:
    - name: http
      port: 80
      targetPort: http
